version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: insidechurch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: insidechurch
      DB_SSLMODE: disable
      JWT_SECRET: sua_chave_secreta
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["./insidechurch"]

volumes:
  pgdata: 